FROM openjdk:22-jdk
RUN mkdir /opt/app
COPY /target/ConfigService-0.0.1-SNAPSHOT.jar /opt/app/ConfigService.jar
RUN mkdir /opt/ConfigRepository
RUN mkdir /opt/ConfigRepository/AuthenticationService
RUN mkdir /opt/ConfigRepository/SpotifyChecker
COPY AuthenticationService-dev.properties /opt/ConfigRepository/AuthenticationService
CMD ["java", "-jar", "/opt/app/ConfigService.jar"]